version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh /data/recruitment/start.local.bat
    environment:
      - server_params=--settings=settings.local
    volumes:
      - .:/data/recruitment
      - /data/logs/recruitment/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - flower
  redis:
    image: "redis:alpine"
    container_name: recruit-redis
    ports:
      - "6379:6379"
  celery:
    image: "ihopeit/django-recruitment:0.8"
    container_name: recruit-celery
    volumes:
      - .:/data/recruitment
      - /data/logs/recruitment/
    entrypoint: ["/bin/sh", "/data/recruitment/worker.start.sh"]
    depends_on: 
      - redis
  flower:
    image: "ihopeit/django-recruitment:0.8"
    container_name: recruit-flower
    ports:
      - "5555:5555"
    volumes:
      - .:/data/recruitment
      - /data/logs/recruitment/
    entrypoint: ["/bin/sh", "/data/recruitment/flower.start.sh"]
    depends_on: 
      - redis
      